### ISSUE TITLE
Update automation workflow module to build clean and success

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-maximo#11]

**Comment by balasgit** [comment]
Tom - moving this issues since you are active with Maximo updating

**Comment by tcskill** [comment]
@balasgit Should this be closed?

**Comment by balasgit** [comment]
@tcskill -no.. this needs to be implemented. Here is the sample which you can refer and implement similar for the 5 files under the workflow folder.

https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2wh-service/tree/main/.github/workflows

**Comment by tcskill** [comment]
@balasgit oh ok, i wasn't sure what the ask was, so you want basically a test workflow added, ok

**Comment by balasgit** [comment]
Thats correct. Ping me on slack if any questions. appreciated your effort

**Comment by tcskill** [comment]
closing - stale issue that has been addressed by recent releases and shift to the ansible operator here: https://github.com/cloud-native-toolkit/operator-masauto
